export const BLOGS_FETCHED = 'BLOGS_FETCHED';
export const BLOGS_FETCHED_FAILURE = 'BLOGS_FETCHED_FAILURE';
export const BLOG_OPENED = 'BLOG_OPENED';
export const BLOG_OPENED_FAILURE = 'BLOG_OPENED_FAILURE';
